# Generated by Django 3.1.2 on 2020-12-22 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0012_index_additions"),
        ("blueprints", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app"),
                    ("request_blueprints", "Can request blueprints"),
                    ("manage_requests", "Can review and accept blueprint requests"),
                    (
                        "add_personal_blueprint_owner",
                        "Can add personal blueprint owners",
                    ),
                    (
                        "add_corporate_blueprint_owner",
                        "Can add corporate blueprint owners",
                    ),
                    ("view_alliance_blueprints", "Can view alliance's blueprints"),
                    (
                        "view_industry_jobs",
                        "Can view details about running industry jobs",
                    ),
                ),
            },
        ),
        migrations.CreateModel(
            name="IndustryJob",
            fields=[
                (
                    "id",
                    models.PositiveBigIntegerField(
                        help_text="Eve Online job ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "activity",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Manufacturing"),
                            (2, "Researching Technology"),
                            (3, "Researching Time Efficiency"),
                            (4, "Researching Material Efficiency"),
                            (5, "Copying"),
                            (6, "Duplicating"),
                            (7, "Reverse Engineering"),
                            (8, "Inventing"),
                            (9, "Reacting"),
                        ]
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("runs", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("delivered", "Delivered"),
                            ("paused", "Paused"),
                            ("ready", "Ready"),
                            ("reverted", "Reverted"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "blueprint",
                    models.OneToOneField(
                        help_text="Blueprint the job is running",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blueprints.blueprint",
                    ),
                ),
                (
                    "installer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Eve Online location ID of the facility in which the job is running",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="blueprints.location",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="blueprints.owner",
                    ),
                ),
            ],
        ),
    ]
